### ISSUE TITLE
fast rotation loses signals

### ISSUE THREAD

**Issue by Phlip** [nstansby/rpi-rotary-encoder-python#3]
I used this code on a Pi with a US Digital S5-4096-250-IE-S-D rotary quadrature encoder, which a big wheel on its axle

When I slowly rotate the wheel once, I can successfully count up to 4096 ticks.

But when I rotate quickly, we only count up to 200. This implies the Python does not sample the GPIO signals fast enough.

**Comment by nstansby** [comment]
Please see the README file:

1. The code uses interrupts, not polling.  It's not an issue of not sampling the GPIO signals fast enough; the problem is that it's not a very fast CPU, and it's not running on a real-time OS.  It simply can not keep up with the number of events that are happening.
1. There is an open issue #2 to gracefully handle fast rotation by increasing the step size when it detects the user is spinning fast.  This won't necessarily be accurate (the final value won't exactly match the number of steps the encode went through), but it does let you get to larger values quickly while still letting you fine tune to a precise value once you're close.
